version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_sqlmodel
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ps_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    networks:
      - backend
  
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy 
    command: ["/bin/sh", "-c", "alembic upgrade head && uvicorn server:app --reload --workers 1 --host 0.0.0.0 --port 8000"]
    networks:
      - backend
    ports:
      - "8010:8000"
    volumes:
      - ./src/api/:/api
    env_file:
      - .env

volumes:
  ps_data:

networks:
  backend: