"""update table

Revision ID: 7faa5c762f53
Revises: b19047fc3d90
Create Date: 2025-02-26 17:56:19.208678

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7faa5c762f53'
down_revision = 'b19047fc3d90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
    sa.Column('iata_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('airline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_table('airport',
    sa.Column('iata_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('airport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('iata_code')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('airline_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('flight_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tail_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('origin_airport_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('destination_airport_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_departure', sa.Integer(), nullable=True),
    sa.Column('departure_time', sa.Integer(), nullable=True),
    sa.Column('departure_delay', sa.Integer(), nullable=True),
    sa.Column('taxi_out', sa.Integer(), nullable=True),
    sa.Column('wheels_off', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.Integer(), nullable=True),
    sa.Column('elapsed_time', sa.Integer(), nullable=True),
    sa.Column('air_time', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('wheels_on', sa.Integer(), nullable=True),
    sa.Column('taxi_in', sa.Integer(), nullable=True),
    sa.Column('scheduled_arrival', sa.Integer(), nullable=True),
    sa.Column('arrival_time', sa.Integer(), nullable=True),
    sa.Column('arrival_delay', sa.Integer(), nullable=True),
    sa.Column('diverted', sa.Integer(), nullable=True),
    sa.Column('cancelled', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('air_system_delay', sa.Integer(), nullable=True),
    sa.Column('security_delay', sa.Integer(), nullable=True),
    sa.Column('airline_delay', sa.Integer(), nullable=True),
    sa.Column('late_aircraft_delay', sa.Integer(), nullable=True),
    sa.Column('weather_delay', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['airline_id'], ['airline.iata_code'], ),
    sa.ForeignKeyConstraint(['destination_airport_id'], ['airport.iata_code'], ),
    sa.ForeignKeyConstraint(['origin_airport_id'], ['airport.iata_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    op.drop_table('airport')
    op.drop_table('airline')
    # ### end Alembic commands ###
